package ch.owt.boatapp.bff.adapter.in.web;

import ch.owt.boatapp.bff.adapter.in.web.dto.generated.UserInfoResponse;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.ResponseEntity;
import org.springframework.security.core.Authentication;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.security.oauth2.core.oidc.user.OidcUser;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RestController;

import java.util.UUID;

/**
 * BFF-only authentication endpoints. Returns the profile of the currently
 * authenticated user — read from the OAuth2 session ({@link OidcUser}) when
 * present, falling back to a hardcoded dummy dev user otherwise.
 *
 * <p>This endpoint is NOT proxied to the Business Service: the user profile
 * lives only in the BFF's session. The {@link UserInfoResponse} DTO is
 * generated by the BFF's own openapi-generator execution from the {@code User}
 * tag in {@code contracts/openapi.yaml} (the Business Service codegen filters
 * that tag out).
 *
 * <p>Step 02a3 supplies a minimal body — full OidcUser-claim mapping moves
 * to {@code BffSecurityHelper} in step 02a4 once the OAuth2 client wiring lands.
 */
@RestController
public class AuthController {

    private static final Logger log = LoggerFactory.getLogger(AuthController.class);

    /** Dummy dev user id — kept in sync with {@code business-service}'s {@code SecurityHelper.DEV_USER_ID}. */
    private static final UUID DEV_USER_ID =
            UUID.fromString("99999999-9999-9999-9999-999999999999");

    /**
     * Return the profile of the authenticated user.
     *
     * <p>When an OAuth2 session is present, projects the {@link OidcUser}
     * claims ({@code sub}/{@code preferred_username}/{@code email}/
     * {@code given_name}/{@code family_name}) into a {@link UserInfoResponse}.
     * Otherwise (dev mode in 02a3, before {@code SecurityFilterChain} is
     * wired) returns the dummy dev user.
     *
     * @return 200 OK with the user profile
     */
    @GetMapping("/api/me")
    public ResponseEntity<UserInfoResponse> getCurrentUser() {
        Authentication auth = SecurityContextHolder.getContext().getAuthentication();
        if (auth != null && auth.getPrincipal() instanceof OidcUser oidcUser) {
            UserInfoResponse response = fromOidcUser(oidcUser);
            log.info("/api/me from OidcUser sub={}", oidcUser.getSubject());
            return ResponseEntity.ok(response);
        }
        log.info("/api/me dev fallback (no OAuth2 session)");
        return ResponseEntity.ok(devUser());
    }

    private static UserInfoResponse fromOidcUser(OidcUser oidcUser) {
        UUID id;
        try {
            id = UUID.fromString(oidcUser.getSubject());
        } catch (IllegalArgumentException ex) {
            // A real Keycloak `sub` is always a UUID; non-UUID `sub` indicates an
            // identity-provider misconfiguration. Surface as 500 (via the global
            // fallback handler) rather than masquerading as the dev sentinel.
            log.error("OidcUser sub is not a UUID — IDP misconfigured? sub={}", oidcUser.getSubject(), ex);
            throw new IllegalStateException("OidcUser sub is not a valid UUID", ex);
        }
        return new UserInfoResponse(
                id,
                stringClaim(oidcUser, "preferred_username", "unknown"),
                stringClaim(oidcUser, "email", "unknown@example.com"),
                stringClaim(oidcUser, "given_name", ""),
                stringClaim(oidcUser, "family_name", ""));
    }

    private static String stringClaim(OidcUser oidcUser, String name, String fallback) {
        Object value = oidcUser.getClaim(name);
        return value != null ? value.toString() : fallback;
    }

    private static UserInfoResponse devUser() {
        return new UserInfoResponse(DEV_USER_ID, "dev-user", "dev@example.com", "Dev", "User");
    }
}
